name: labelmaker
channels:
  - defaults
dependencies:
  - python=3.10
  - conda-forge::libstdcxx-ng # for open3d's headless rendering
  - pip
  # cuda version not decided yet
  - conda-forge::gxx=11.4.0
  - nvidia/label/cuda-11.8.0::cuda
